
poss_sheet_old = [[[], ['N-N=N'], ['blank', []]],
 [['N-N=N'], ['N-0=0'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [[],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['blank', []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], ['N-N=N'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  [],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['gd-pt'], ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]



poss_sheet_list = [[['incomplete'], ['N-N=N', 'incomplete'], ['blank', [], 'incomplete']],
 [['N-N=N', 'incomplete'], ['incomplete', 'N-0=0'], ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [['incomplete'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0'],
   'incomplete'],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['blank', [], 'incomplete'],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'incomplete'],
  ['incomplete'],
  ['incomplete']],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], 'incomplete', ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['N-0=0', 'incomplete'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt'], 'incomplete', ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['incomplete'],
  ['incomplete']],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]


poss_sheet_before_copy_identification = [[{'pos': -2, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'}],
 [{'pos': -2, 'type': ['blank', 'pt-gd=?']},
  {'pos': -2, 'type': ['blank', 'gd-pt']},
  {'pos': -2, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -2, 'type': ['blank', '0-N=N']},
  {'pos': -2, 'type': ['blank', 'pt-gd=0']},
  {'pos': -2, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -2, 'type': ['blank', '0-N=0']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'N-N=N']},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -4, 'type': ['blank', 'correct_col']},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': '0-N=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': '0-N=N'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': ['blank', 'correct_col']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -3, 'type': ['blank', 'pt-gd=0']},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', '0-N=0']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -5, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -4, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'pt-gd=0']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', '0-N=0']},
  {'pos': -5, 'type': ['blank', 'gd-pt']},
  {'pos': -5, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -5, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -3, 'type': ['blank', 'pt-gd=0']},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', '0-N=0']},
  {'pos': -4, 'type': ['blank', 'correct_col']},
  {'pos': -3, 'type': 'incomplete'}]]


poss_sheet = [[{'pos': -2, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'}],
 [{'pos': -2, 'type': ['blank', 'gd-pt']},
  {'pos': -2, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -2, 'type': ['blank', '0-N=N']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -4, 'type': ['blank', 'correct_col']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': '0-N=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': '0-N=N'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': ['blank', 'correct_col']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -4, 'type': ['blank', '0-N=N']},
  {'pos': -5, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'correct_col']}]]
