
poss_sheet_old = [[[], ['N-N=N'], ['blank', []]],
 [['N-N=N'], ['N-0=0'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [[],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['blank', []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], ['N-N=N'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  [],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['gd-pt'], ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]



poss_sheet = [[['incomplete'], ['N-N=N', 'incomplete'], ['blank', [], 'incomplete']],
 [['N-N=N', 'incomplete'], ['incomplete', 'N-0=0'], ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [['incomplete'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0'],
   'incomplete'],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['blank', [], 'incomplete'],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'incomplete'],
  ['incomplete'],
  ['incomplete']],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], 'incomplete', ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['N-0=0', 'incomplete'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt'], 'incomplete', ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['incomplete'],
  ['incomplete']],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]
