#!/usr/bin/env python
# -*- coding: utf-8 -*-

poss_sheet_old = [[[], ['N-N=N'], ['blank', []]],
 [['N-N=N'], ['N-0=0'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [[],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['blank', []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], ['N-N=N'], []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  [],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['gd-pt'], ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'], [], []],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]

poss_sheet_list = [[['incomplete'], ['N-N=N', 'incomplete'], ['blank', [], 'incomplete']],
 [['N-N=N', 'incomplete'], ['incomplete', 'N-0=0'], ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'], []],
 [['incomplete'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0'],
   'incomplete'],
  ['blank', ['N-N=N'], []],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', '0-N=0', 'gd-pt', 'pt-gd=gd', '0-N=N'],
  []],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['blank', [], 'incomplete'],
  ['blank', []]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'incomplete'],
  ['incomplete'],
  ['incomplete']],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'pt-gd=0', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N', 'incomplete'],
  ['incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], 'incomplete', ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank', ['pt-gd=?'], ['pt-gd=pt'], ['gd-pt'], ['pt-gd=gd']]],
 [['N-0=0'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['incomplete']],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd', 'incomplete'],
  ['N-0=0', 'incomplete'],
  ['pt-gd=?',
   'gd-pt',
   'pt-gd=gd',
   '0-N=N',
   'pt-gd=0',
   'pt-gd=pt',
   '0-N=0',
   'incomplete'],
  ['blank', ['pt-gd=?'], ['gd-pt'], 'incomplete', ['pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['incomplete'],
  ['incomplete']],
 [[],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'gd-pt', 'pt-gd=pt', 'pt-gd=gd'],
  ['N-N=N'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', ['pt-gd=?'], ['gd-pt', 'pt-gd=pt'], ['pt-gd=gd']]],
 [['pt-gd=?', 'pt-gd=0', 'pt-gd=pt', 'gd-pt', 'pt-gd=gd'],
  ['pt-gd=?', 'gd-pt', 'pt-gd=gd', '0-N=N', 'pt-gd=0', 'pt-gd=pt', '0-N=0'],
  ['blank',
   ['pt-gd=?'],
   ['gd-pt', 'pt-gd=gd', '0-N=N'],
   ['pt-gd=0', 'pt-gd=pt', '0-N=0']],
  ['blank', []]]]

poss_sheet_before_copy_identification = [[{'pos': -2, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'}],
 [{'pos': -2, 'type': ['blank', 'pt-gd=?']},
  {'pos': -2, 'type': ['blank', 'gd-pt']},
  {'pos': -2, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -2, 'type': ['blank', '0-N=N']},
  {'pos': -2, 'type': ['blank', 'pt-gd=0']},
  {'pos': -2, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -2, 'type': ['blank', '0-N=0']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'N-N=N']},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -4, 'type': ['blank', 'correct_col']},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': '0-N=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': '0-N=N'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': ['blank', 'correct_col']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -3, 'type': ['blank', 'pt-gd=0']},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', '0-N=0']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': 'pt-gd=?'},
  {'pos': -4, 'type': ['blank', 'pt-gd=?']},
  {'pos': -5, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -4, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'pt-gd=0']},
  {'pos': -4, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -4, 'type': ['blank', '0-N=0']},
  {'pos': -5, 'type': ['blank', 'gd-pt']},
  {'pos': -5, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -5, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=?'},
  {'pos': -2, 'type': 'pt-gd=?'},
  {'pos': -3, 'type': ['blank', 'pt-gd=?']},
  {'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -3, 'type': ['blank', 'pt-gd=0']},
  {'pos': -3, 'type': ['blank', 'pt-gd=pt']},
  {'pos': -3, 'type': ['blank', '0-N=0']},
  {'pos': -4, 'type': ['blank', 'correct_col']},
  {'pos': -3, 'type': 'incomplete'}]]

poss_sheet_without_results = [[{'pos': -2, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-N=N'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'}],
 [{'pos': -2, 'type': ['blank', 'gd-pt']},
  {'pos': -2, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -2, 'type': ['blank', '0-N=N']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']},
  {'pos': -4, 'type': ['blank', 'correct_col']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': '0-N=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': '0-N=N'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': ['blank', 'correct_col']},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': ['blank', 'correct_col']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -2, 'type': 'incomplete'},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'N-0=0'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -3, 'type': 'incomplete'}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-0=0'},
  {'pos': -1, 'type': 'incomplete'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': 'incomplete'},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'incomplete'}],
 [{'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'N-N=N'},
  {'pos': -3, 'type': 'gd-pt'},
  {'pos': -3, 'type': 'pt-gd=gd'},
  {'pos': -3, 'type': '0-N=N'},
  {'pos': -3, 'type': 'pt-gd=0'},
  {'pos': -3, 'type': 'pt-gd=pt'},
  {'pos': -3, 'type': '0-N=0'},
  {'pos': -4, 'type': ['blank', 'gd-pt']},
  {'pos': -4, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -4, 'type': ['blank', '0-N=N']},
  {'pos': -5, 'type': ['blank', 'pt-gd=gd']}],
 [{'pos': -1, 'type': 'pt-gd=0'},
  {'pos': -1, 'type': 'pt-gd=pt'},
  {'pos': -1, 'type': 'gd-pt'},
  {'pos': -1, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': 'gd-pt'},
  {'pos': -2, 'type': 'pt-gd=gd'},
  {'pos': -2, 'type': '0-N=N'},
  {'pos': -2, 'type': 'pt-gd=0'},
  {'pos': -2, 'type': 'pt-gd=pt'},
  {'pos': -2, 'type': '0-N=0'},
  {'pos': -3, 'type': ['blank', 'gd-pt']},
  {'pos': -3, 'type': ['blank', 'pt-gd=gd']},
  {'pos': -3, 'type': ['blank', '0-N=N']},
  {'pos': -4, 'type': ['blank', 'correct_col']}]]

poss_sheet_without_correct = [[{'pos': -2, 'result': '4', 'type': 'N-N=N'},
  {'pos': -1, 'result': '02', 'type': 'incomplete'},
  {'pos': -3, 'result': '2', 'type': 'blank_correct_col'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '5', 'type': 'N-N=N'},
  {'pos': -1, 'result': '80', 'type': 'incomplete'},
  {'pos': -2, 'result': '0', 'type': 'N-0=0'},
  {'pos': -2, 'result': '68', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'}],
 [{'pos': -2, 'result': '3', 'type': 'blank_gd-pt'},
  {'pos': -2, 'result': '3', 'type': 'blank_pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'blank_0-N=N'},
  {'pos': -1, 'result': '02', 'type': 'incomplete'},
  {'pos': -3, 'result': '0', 'type': 'blank_correct_col'},
  {'pos': -4, 'result': '5', 'type': 'blank_correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '0', 'type': '0-N=0'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -1, 'result': '3', 'type': '0-N=N'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'gd-pt'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'blank_correct_col'},
  {'pos': -1, 'result': '59', 'type': 'incomplete'},
  {'pos': -3, 'result': '2', 'type': 'blank_correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'gd-pt'},
  {'pos': -1, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -1, 'result': '06', 'type': 'incomplete'},
  {'pos': -2, 'result': '61', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'N-0=0'},
  {'pos': -2, 'result': '7', 'type': 'gd-pt'},
  {'pos': -2, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '7', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '6', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '7', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '6', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '8', 'type': 'gd-pt'},
  {'pos': -2, 'result': '9', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '12', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '2', 'type': 'gd-pt'},
  {'pos': -2, 'result': '6', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '3', 'type': 'gd-pt'},
  {'pos': -3, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -4, 'result': '7', 'type': 'blank_gd-pt'},
  {'pos': -4, 'result': '8', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '6', 'type': 'gd-pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '9', 'type': 'N-N=N'},
  {'pos': -3, 'result': '1', 'type': 'gd-pt'},
  {'pos': -3, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '39', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -2, 'result': '10', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '5', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'},
  {'pos': -3, 'result': '16', 'type': 'incomplete'},
  {'pos': -4, 'result': '2', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'gd-pt'},
  {'pos': -1, 'result': '9', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'gd-pt'},
  {'pos': -2, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '3', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'N-0=0'},
  {'pos': -2, 'result': '8', 'type': 'gd-pt'},
  {'pos': -2, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '8', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '8', 'type': 'gd-pt'},
  {'pos': -3, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '8', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '22', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'N-0=0'},
  {'pos': -1, 'result': '08', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'gd-pt'},
  {'pos': -3, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '6', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -4, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '34', 'type': 'incomplete'},
  {'pos': -4, 'result': '6', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '6', 'type': 'gd-pt'},
  {'pos': -1, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'}],
 [{'pos': -2, 'result': '4', 'type': 'gd-pt'},
  {'pos': -2, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '4', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '4', 'type': 'blank_pt-gd=gd'},
  {'pos': -3, 'result': '4', 'type': 'blank_0-N=N'},
  {'pos': -4, 'result': '4', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -3, 'result': '2', 'type': 'gd-pt'},
  {'pos': -3, 'result': '2', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '2', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -4, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -4, 'result': '2', 'type': 'blank_pt-gd=gd'},
  {'pos': -4, 'result': '2', 'type': 'blank_0-N=N'},
  {'pos': -5, 'result': '2', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': 'gd-pt'},
  {'pos': -2, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '4', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '4', 'type': 'blank_pt-gd=gd'},
  {'pos': -3, 'result': '4', 'type': 'blank_0-N=N'},
  {'pos': -4, 'result': '4', 'type': 'blank_correct_col'}]]

poss_sheet = [[{'pos': -1, 'result': '2', 'type': 'correct_col'},
  {'pos': -2, 'result': '4', 'type': 'N-N=N'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -1, 'result': '02', 'type': 'incomplete'},
  {'pos': -3, 'result': '2', 'type': 'blank_correct_col'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'copy'}],
 [{'pos': -1, 'result': '0', 'type': 'correct_col'},
  {'pos': -1, 'result': '5', 'type': 'N-N=N'},
  {'pos': -1, 'result': '80', 'type': 'incomplete'},
  {'pos': -2, 'result': '8', 'type': 'correct_col'},
  {'pos': -2, 'result': '0', 'type': 'N-0=0'},
  {'pos': -3, 'result': '6', 'type': 'correct_col'},
  {'pos': -2, 'result': '68', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '2', 'type': 'correct_col'},
  {'pos': -2, 'result': '3', 'type': 'blank_gd-pt'},
  {'pos': -2, 'result': '3', 'type': 'blank_pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'blank_0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'copy'},
  {'pos': -1, 'result': '02', 'type': 'incomplete'},
  {'pos': -3, 'result': '3', 'type': 'copy'},
  {'pos': -3, 'result': '0', 'type': 'blank_correct_col'},
  {'pos': -4, 'result': '5', 'type': 'blank_correct_col'},
  {'pos': -4, 'result': '8', 'type': 'copy'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '0', 'type': '0-N=0'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -1, 'result': '3', 'type': '0-N=N'},
  {'pos': -2, 'result': '3', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'gd-pt'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'blank_correct_col'},
  {'pos': -1, 'result': '59', 'type': 'incomplete'},
  {'pos': -2, 'result': '6', 'type': 'copy'},
  {'pos': -3, 'result': '2', 'type': 'blank_correct_col'},
  {'pos': -3, 'result': '5', 'type': 'copy'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'gd-pt'},
  {'pos': -1, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'correct_col'},
  {'pos': -1, 'result': '06', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'correct_col'},
  {'pos': -2, 'result': '61', 'type': 'incomplete'}],
 [{'pos': -1, 'result': '0', 'type': 'N-0=0'},
  {'pos': -1, 'result': '6', 'type': 'correct_col'},
  {'pos': -2, 'result': '7', 'type': 'gd-pt'},
  {'pos': -2, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '7', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '1', 'type': 'copy'},
  {'pos': -3, 'result': '6', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '7', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '6', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '8', 'type': 'gd-pt'},
  {'pos': -2, 'result': '9', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '12', 'type': 'incomplete'},
  {'pos': -3, 'result': '2', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '2', 'type': 'gd-pt'},
  {'pos': -2, 'result': '6', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '3', 'type': 'gd-pt'},
  {'pos': -3, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -4, 'result': '1', 'type': 'copy'},
  {'pos': -4, 'result': '7', 'type': 'blank_gd-pt'},
  {'pos': -4, 'result': '8', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '6', 'type': 'gd-pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '9', 'type': 'N-N=N'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -3, 'result': '1', 'type': 'gd-pt'},
  {'pos': -3, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '39', 'type': 'incomplete'},
  {'pos': -4, 'result': '4', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '3', 'type': 'gd-pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -2, 'result': '10', 'type': 'incomplete'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -3, 'result': '1', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '5', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'correct_col'},
  {'pos': -4, 'result': '1', 'type': 'copy'},
  {'pos': -3, 'result': '16', 'type': 'incomplete'},
  {'pos': -4, 'result': '2', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'gd-pt'},
  {'pos': -1, 'result': '9', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': 'gd-pt'},
  {'pos': -2, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '3', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '1', 'type': 'copy'},
  {'pos': -3, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '3', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'N-0=0'},
  {'pos': -1, 'result': '7', 'type': 'correct_col'},
  {'pos': -2, 'result': '8', 'type': 'gd-pt'},
  {'pos': -2, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '8', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '8', 'type': 'gd-pt'},
  {'pos': -3, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '8', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '22', 'type': 'incomplete'},
  {'pos': -4, 'result': '3', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '5', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '7', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'correct_col'},
  {'pos': -2, 'result': '0', 'type': 'N-0=0'},
  {'pos': -1, 'result': '08', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'gd-pt'},
  {'pos': -3, 'result': '6', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '6', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -4, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '34', 'type': 'incomplete'},
  {'pos': -4, 'result': '4', 'type': 'copy'},
  {'pos': -4, 'result': '6', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '6', 'type': 'gd-pt'},
  {'pos': -1, 'result': '8', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -2, 'result': '60', 'type': 'incomplete'},
  {'pos': -3, 'result': '6', 'type': 'correct_col'}],
 [{'pos': -1, 'result': '4', 'type': 'correct_col'},
  {'pos': -2, 'result': '4', 'type': 'gd-pt'},
  {'pos': -2, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '4', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '4', 'type': 'blank_pt-gd=gd'},
  {'pos': -3, 'result': '4', 'type': 'blank_0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'copy'},
  {'pos': -4, 'result': '2', 'type': 'copy'},
  {'pos': -4, 'result': '4', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '2', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '1', 'type': 'N-N=N'},
  {'pos': -2, 'result': '0', 'type': 'correct_col'},
  {'pos': -3, 'result': '2', 'type': 'gd-pt'},
  {'pos': -3, 'result': '2', 'type': 'pt-gd=gd'},
  {'pos': -3, 'result': '2', 'type': '0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -3, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -3, 'result': '0', 'type': '0-N=0'},
  {'pos': -4, 'result': '2', 'type': 'blank_gd-pt'},
  {'pos': -4, 'result': '2', 'type': 'blank_pt-gd=gd'},
  {'pos': -4, 'result': '2', 'type': 'blank_0-N=N'},
  {'pos': -4, 'result': '0', 'type': 'copy'},
  {'pos': -5, 'result': '1', 'type': 'copy'},
  {'pos': -5, 'result': '2', 'type': 'blank_pt-gd=gd'}],
 [{'pos': -1, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -1, 'result': '1', 'type': 'pt-gd=pt'},
  {'pos': -1, 'result': '2', 'type': 'gd-pt'},
  {'pos': -1, 'result': '3', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': 'gd-pt'},
  {'pos': -2, 'result': '4', 'type': 'pt-gd=gd'},
  {'pos': -2, 'result': '4', 'type': '0-N=N'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=0'},
  {'pos': -2, 'result': '0', 'type': 'pt-gd=pt'},
  {'pos': -2, 'result': '0', 'type': '0-N=0'},
  {'pos': -3, 'result': '4', 'type': 'blank_gd-pt'},
  {'pos': -3, 'result': '4', 'type': 'blank_pt-gd=gd'},
  {'pos': -3, 'result': '4', 'type': 'blank_0-N=N'},
  {'pos': -3, 'result': '0', 'type': 'copy'},
  {'pos': -4, 'result': '4', 'type': 'blank_correct_col'},
  {'pos': -4, 'result': '8', 'type': 'copy'}]]

